[package]
name = "dioxus-todo-sample"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus.workspace = true
dioxus-logger.workspace = true
log.workspace = true
strum.workspace = true
dioxus-web = "0.4.3"

components = { path = "../components" }
models = { path = "../models" }
